version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - /home/roman/db/sqlite:/usr/src/app/data
    command: >
      sh -c "npm start"
